version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  service1:
    container_name: nginx_service1
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./service1/:/var/www/
    networks:
      - envoymesh
    expose:
      - "80"
    ports:
      - "8010:80"

  service2:
    container_name: nginx_service2
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./service2/:/var/www/
    networks:
      - envoymesh
    expose:
      - "80"
    ports:
      - "8020:80"

networks:
  envoymesh: {}
